In [1]:
import torch

# Autograd

## Experiment

1. Create a tensor.
2. Run the following 4 operations on the tensor, in the same order:
  - multiply a random tensor (same tensor, with requires_grad=True)
  - multiply by a scalar (same scalar, with requires_grad=True)
  - sum the elements of the results to get the output.

3. The expected output is pre decided (not necessary to be the same as the sum from the above step)
4. perform back propagation using tensor.backward() and then manually calculating gradients. Compare their speed.

In [2]:
# Input tensors
x = torch.rand((10000))

In [3]:
# Output
y = 10

In [4]:
x

tensor([0.1863, 0.3895, 0.6074,  ..., 0.8275, 0.6921, 0.2658])

In [5]:
# random tensor
random_tensor = torch.rand((10000), requires_grad=True)
# random scalar
random_scalar = torch.rand((1, 1), requires_grad=True)

In [6]:
random_tensor

tensor([0.6507, 0.5699, 0.2666,  ..., 0.0865, 0.8702, 0.9336],
       requires_grad=True)

In [7]:
random_scalar

tensor([[0.8961]], requires_grad=True)

### Operations

In [8]:
x_1 = x * random_tensor

In [9]:
x_1

tensor([0.1212, 0.2220, 0.1619,  ..., 0.0716, 0.6023, 0.2482],
       grad_fn=<MulBackward0>)

In [10]:
x_2 = x_1 * random_scalar

In [11]:
x_2

tensor([[0.1086, 0.1989, 0.1451,  ..., 0.0642, 0.5397, 0.2224]],
       grad_fn=<MulBackward0>)

### Sum

In [12]:
x_3 = x_2.sum()

In [13]:
x_3

tensor(2250.9272, grad_fn=<SumBackward0>)

### Manual Backpropagation

In [111]:
loss = x_3 - y

In [112]:
loss

tensor(-5.2600, grad_fn=<SubBackward0>)

loss = x2.sum() - y

loss = (x_1 * random_scalar).sum() - y

dL/d(random_scalar) = (x_1 * (d(random_scalar)/d(random_scalar))).sum() - y * (d(1)/d(random_scalar))

dL/d(random_scalar) = x_1.sum() - 0

dL/d(random_scalar) = (x * random_tensor).sum() = dx_2

In [113]:
dx_2 = (x*random_tensor).sum()

loss = x2.sum() - y

loss = (x_1 * random_scalar).sum() - y

loss = (x * random_tensor * random_scalar).sum() - y

dL/d(random_tensor) = (x * random_scalar * (d(random_tensor)/d(random_tensor))) - y * (d(1)/d(random_tensor))

--- .sum() is removed because random_tensor is a vector

dL/d(random_tensor) = (x * random_scalar) - 0

dL/d(random_tensor) = (x * random_scalar) = dx_1

In [116]:
dx_1 = x*random_scalar

In [117]:
dx_1, dx_2

(tensor([[0.8578, 1.7156, 2.5734, 3.4312]], grad_fn=<MulBackward0>),
 tensor(5.5258, grad_fn=<SumBackward0>))

### Autograd

In [119]:
loss.backward()

In [122]:
loss

tensor(-5.2600, grad_fn=<SubBackward0>)

In [123]:
random_tensor.grad, random_scalar.grad

(tensor([0.8578, 1.7156, 2.5734, 3.4312]), tensor([[5.5258]]))

## Timing test

In [14]:
# Manual
%%time
loss = x_3 - y
dx_2 = (x*random_tensor).sum()
dx_1 = x*random_scalar
dx_1, dx_2

CPU times: user 993 µs, sys: 0 ns, total: 993 µs
Wall time: 1.05 ms


(tensor([[0.1669, 0.3490, 0.5443,  ..., 0.7416, 0.6202, 0.2382]],
        grad_fn=<MulBackward0>),
 tensor(2511.7842, grad_fn=<SumBackward0>))

In [15]:
# Autograd
%%time
loss = x_3 - y
loss.backward()
random_tensor.grad, random_scalar.grad

CPU times: user 2.15 ms, sys: 7 µs, total: 2.16 ms
Wall time: 1.59 ms


(tensor([0.1669, 0.3490, 0.5443,  ..., 0.7416, 0.6202, 0.2382]),
 tensor([[2511.7842]]))