In [1]:
import torch

# Indexing

**Goal**

Understand how data is selected, modified, and shared.

## Basic Indexing

Indexing by rows, columns, etc. Check if indexing copies memory

In [2]:
# create tensor
tensor = torch.rand((10, 100, 50))

In [3]:
tensor

tensor([[[0.5674, 0.2660, 0.3655,  ..., 0.9963, 0.1173, 0.7111],
         [0.6913, 0.0730, 0.3406,  ..., 0.5935, 0.3029, 0.3444],
         [0.6760, 0.4835, 0.4576,  ..., 0.1608, 0.6673, 0.6725],
         ...,
         [0.9980, 0.3304, 0.1001,  ..., 0.6589, 0.3593, 0.7914],
         [0.8219, 0.2910, 0.7093,  ..., 0.7217, 0.3240, 0.4031],
         [0.3762, 0.0160, 0.8726,  ..., 0.0917, 0.2377, 0.0158]],

        [[0.2411, 0.6337, 0.6570,  ..., 0.4872, 0.7354, 0.6634],
         [0.3013, 0.6390, 0.9093,  ..., 0.4288, 0.0022, 0.1392],
         [0.5041, 0.4968, 0.5568,  ..., 0.7174, 0.1225, 0.8386],
         ...,
         [0.4277, 0.1144, 0.7661,  ..., 0.9134, 0.1157, 0.3811],
         [0.5524, 0.3117, 0.3174,  ..., 0.1314, 0.0292, 0.3745],
         [0.5427, 0.6873, 0.8224,  ..., 0.0853, 0.6380, 0.0621]],

        [[0.1453, 0.6639, 0.7692,  ..., 0.3518, 0.6201, 0.7935],
         [0.5982, 0.7738, 0.7061,  ..., 0.5006, 0.1488, 0.6536],
         [0.8294, 0.8346, 0.2343,  ..., 0.8208, 0.7959, 0.

In [4]:
tensor.shape, tensor.dtype

(torch.Size([10, 100, 50]), torch.float32)

In [7]:
tensor[9], tensor[9].shape

(tensor([[0.2874, 0.6549, 0.1598,  ..., 0.1183, 0.3668, 0.2451],
         [0.1895, 0.7135, 0.4930,  ..., 0.8175, 0.7019, 0.6825],
         [0.8187, 0.1695, 0.8278,  ..., 0.5270, 0.7272, 0.1619],
         ...,
         [0.6785, 0.0613, 0.2705,  ..., 0.7886, 0.0458, 0.7361],
         [0.9409, 0.3766, 0.8364,  ..., 0.1152, 0.9325, 0.6809],
         [0.5103, 0.2545, 0.2959,  ..., 0.1494, 0.1227, 0.7308]]),
 torch.Size([100, 50]))

In [9]:
tensor[:, 10], tensor[:, 10].shape

(tensor([[9.2809e-01, 1.5258e-01, 2.3511e-01, 9.3724e-01, 6.6410e-01, 3.7750e-01,
          6.5010e-01, 5.0702e-02, 9.8330e-04, 2.6461e-01, 8.9376e-01, 6.0410e-01,
          2.1241e-01, 1.0962e-01, 6.9548e-01, 3.5596e-01, 8.0138e-01, 3.1914e-02,
          6.4403e-01, 1.3267e-01, 6.9946e-02, 1.5636e-01, 2.7885e-01, 5.9008e-01,
          2.8947e-01, 4.5083e-01, 1.5600e-01, 8.3629e-01, 9.7124e-01, 8.1921e-01,
          2.3086e-01, 5.5332e-01, 2.7883e-02, 7.9457e-01, 9.6690e-01, 4.0274e-01,
          2.0735e-01, 1.0850e-01, 1.0713e-01, 7.8657e-01, 4.1911e-01, 5.9000e-01,
          4.3202e-01, 1.9928e-01, 7.7435e-01, 2.5703e-01, 4.9761e-01, 4.8628e-01,
          9.2022e-01, 4.5957e-01],
         [1.8924e-01, 1.5607e-01, 8.1874e-01, 5.3250e-01, 6.3532e-01, 6.7563e-01,
          1.8534e-01, 4.2423e-01, 2.5542e-01, 9.6900e-01, 5.2598e-01, 6.9228e-01,
          6.2667e-01, 3.8488e-01, 3.1669e-01, 8.1981e-01, 1.2352e-01, 7.2986e-01,
          6.6842e-01, 4.2336e-01, 3.6497e-01, 9.1283e-01, 9.841

In [11]:
tensor[:, 10, 2], tensor[:, 10, 2].shape

(tensor([0.2351, 0.8187, 0.7243, 0.6676, 0.0308, 0.1763, 0.3279, 0.1613, 0.3493,
         0.2499]),
 torch.Size([10]))

In [13]:
tensor[3, 20], tensor[3, 20].shape

(tensor([0.6271, 0.5157, 0.8835, 0.2207, 0.1580, 0.9300, 0.9278, 0.0400, 0.8190,
         0.5227, 0.8083, 0.7155, 0.5442, 0.6263, 0.5269, 0.5133, 0.8116, 0.1537,
         0.9744, 0.2629, 0.9534, 0.6329, 0.2289, 0.7835, 0.2512, 0.0170, 0.7473,
         0.4936, 0.8488, 0.3903, 0.5708, 0.7855, 0.6343, 0.6665, 0.3562, 0.1011,
         0.5544, 0.3517, 0.3859, 0.8893, 0.3641, 0.0623, 0.0645, 0.4651, 0.1752,
         0.0982, 0.8348, 0.7390, 0.4408, 0.0119]),
 torch.Size([50]))

In [14]:
tensor[3, 20, 36]

tensor(0.5544)

In [15]:
tensor[-1, 20, 12]

tensor(0.4881)

In [16]:
tensor[-1, -29, :]

tensor([0.0428, 0.0031, 0.2958, 0.3177, 0.1370, 0.6579, 0.7312, 0.3148, 0.7623,
        0.5747, 0.2454, 0.8371, 0.7777, 0.0346, 0.5365, 0.5726, 0.5741, 0.5856,
        0.9387, 0.3204, 0.2000, 0.1996, 0.2158, 0.8318, 0.7106, 0.7980, 0.0083,
        0.6905, 0.6483, 0.3757, 0.7814, 0.9576, 0.6479, 0.4942, 0.1181, 0.5947,
        0.5420, 0.9229, 0.9943, 0.3351, 0.4512, 0.8592, 0.4934, 0.9419, 0.0481,
        0.7005, 0.5417, 0.1581, 0.6918, 0.7504])

In [20]:
tensor[-1, -29, -28]

tensor(0.2158)

### Questions
Does indexing copy memory?

In [27]:
indexed_tensor = tensor[:, 10, 2]

In [28]:
indexed_tensor

tensor([0.2351, 0.8187, 0.7243, 0.6676, 0.0308, 0.1763, 0.3279, 0.1613, 0.3493,
        0.2499])

In [29]:
tensor[:, 10, 2]

tensor([0.2351, 0.8187, 0.7243, 0.6676, 0.0308, 0.1763, 0.3279, 0.1613, 0.3493,
        0.2499])

In [31]:
tensor[8, 10, 2] = 2721

In [32]:
tensor[8, 10, 2]

tensor(2721.)

In [33]:
indexed_tensor[8]

tensor(2721.)

In [34]:
tensor[:, 10, 2], indexed_tensor

(tensor([2.3511e-01, 8.1874e-01, 7.2431e-01, 6.6759e-01, 3.0818e-02, 1.7635e-01,
         3.2788e-01, 1.6134e-01, 2.7210e+03, 2.4993e-01]),
 tensor([2.3511e-01, 8.1874e-01, 7.2431e-01, 6.6759e-01, 3.0818e-02, 1.7635e-01,
         3.2788e-01, 1.6134e-01, 2.7210e+03, 2.4993e-01]))

### Answer
No! Indexing creates a view of the same tensor based on the index given

## Boolean Indexing

In [21]:
tensor

tensor([[[0.5674, 0.2660, 0.3655,  ..., 0.9963, 0.1173, 0.7111],
         [0.6913, 0.0730, 0.3406,  ..., 0.5935, 0.3029, 0.3444],
         [0.6760, 0.4835, 0.4576,  ..., 0.1608, 0.6673, 0.6725],
         ...,
         [0.9980, 0.3304, 0.1001,  ..., 0.6589, 0.3593, 0.7914],
         [0.8219, 0.2910, 0.7093,  ..., 0.7217, 0.3240, 0.4031],
         [0.3762, 0.0160, 0.8726,  ..., 0.0917, 0.2377, 0.0158]],

        [[0.2411, 0.6337, 0.6570,  ..., 0.4872, 0.7354, 0.6634],
         [0.3013, 0.6390, 0.9093,  ..., 0.4288, 0.0022, 0.1392],
         [0.5041, 0.4968, 0.5568,  ..., 0.7174, 0.1225, 0.8386],
         ...,
         [0.4277, 0.1144, 0.7661,  ..., 0.9134, 0.1157, 0.3811],
         [0.5524, 0.3117, 0.3174,  ..., 0.1314, 0.0292, 0.3745],
         [0.5427, 0.6873, 0.8224,  ..., 0.0853, 0.6380, 0.0621]],

        [[0.1453, 0.6639, 0.7692,  ..., 0.3518, 0.6201, 0.7935],
         [0.5982, 0.7738, 0.7061,  ..., 0.5006, 0.1488, 0.6536],
         [0.8294, 0.8346, 0.2343,  ..., 0.8208, 0.7959, 0.

In [22]:
tensor > 0.5

tensor([[[ True, False, False,  ...,  True, False,  True],
         [ True, False, False,  ...,  True, False, False],
         [ True, False, False,  ..., False,  True,  True],
         ...,
         [ True, False, False,  ...,  True, False,  True],
         [ True, False,  True,  ...,  True, False, False],
         [False, False,  True,  ..., False, False, False]],

        [[False,  True,  True,  ..., False,  True,  True],
         [False,  True,  True,  ..., False, False, False],
         [ True, False,  True,  ...,  True, False,  True],
         ...,
         [False, False,  True,  ...,  True, False, False],
         [ True, False, False,  ..., False, False, False],
         [ True,  True,  True,  ..., False,  True, False]],

        [[False,  True,  True,  ..., False,  True,  True],
         [ True,  True,  True,  ...,  True, False,  True],
         [ True,  True, False,  ...,  True,  True, False],
         ...,
         [False, False, False,  ..., False,  True,  True],
         [

In [24]:
tensor[tensor > 0.5], tensor[tensor > 0.5].shape

(tensor([0.5674, 0.7748, 0.7818,  ..., 0.6889, 0.9989, 0.7308]),
 torch.Size([25035]))

### Questions
Why is this useful in ML?

**Answer:** Let's say we are using the following activation function for a neural network:

  - x >= 0.5 -> return x
  - x < 0.5 -> return 0

 In such an activation function, If the input value is greater than 0.5, it is left as it is, or else it is turned to 0 before moving to next layer. In such a case, we can have the following boolean indexing as a mask:

In [41]:
(tensor > 0.5) * 1

tensor([[[1, 0, 0,  ..., 1, 0, 1],
         [1, 0, 0,  ..., 1, 0, 0],
         [1, 0, 0,  ..., 0, 1, 1],
         ...,
         [1, 0, 0,  ..., 1, 0, 1],
         [1, 0, 1,  ..., 1, 0, 0],
         [0, 0, 1,  ..., 0, 0, 0]],

        [[0, 1, 1,  ..., 0, 1, 1],
         [0, 1, 1,  ..., 0, 0, 0],
         [1, 0, 1,  ..., 1, 0, 1],
         ...,
         [0, 0, 1,  ..., 1, 0, 0],
         [1, 0, 0,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 1, 0]],

        [[0, 1, 1,  ..., 0, 1, 1],
         [1, 1, 1,  ..., 1, 0, 1],
         [1, 1, 0,  ..., 1, 1, 0],
         ...,
         [0, 0, 0,  ..., 0, 1, 1],
         [0, 1, 1,  ..., 1, 0, 1],
         [0, 0, 1,  ..., 1, 0, 0]],

        ...,

        [[0, 0, 0,  ..., 0, 1, 1],
         [0, 1, 0,  ..., 1, 0, 0],
         [1, 1, 1,  ..., 1, 0, 0],
         ...,
         [1, 1, 1,  ..., 1, 0, 1],
         [0, 1, 0,  ..., 0, 1, 0],
         [1, 0, 1,  ..., 0, 0, 1]],

        [[1, 0, 1,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 1, 1, 1],
         [1,

In [39]:
tensor * ((tensor > 0.5) * 1)

tensor([[[0.5674, 0.0000, 0.0000,  ..., 0.9963, 0.0000, 0.7111],
         [0.6913, 0.0000, 0.0000,  ..., 0.5935, 0.0000, 0.0000],
         [0.6760, 0.0000, 0.0000,  ..., 0.0000, 0.6673, 0.6725],
         ...,
         [0.9980, 0.0000, 0.0000,  ..., 0.6589, 0.0000, 0.7914],
         [0.8219, 0.0000, 0.7093,  ..., 0.7217, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.8726,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.0000, 0.6337, 0.6570,  ..., 0.0000, 0.7354, 0.6634],
         [0.0000, 0.6390, 0.9093,  ..., 0.0000, 0.0000, 0.0000],
         [0.5041, 0.0000, 0.5568,  ..., 0.7174, 0.0000, 0.8386],
         ...,
         [0.0000, 0.0000, 0.7661,  ..., 0.9134, 0.0000, 0.0000],
         [0.5524, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.5427, 0.6873, 0.8224,  ..., 0.0000, 0.6380, 0.0000]],

        [[0.0000, 0.6639, 0.7692,  ..., 0.0000, 0.6201, 0.7935],
         [0.5982, 0.7738, 0.7061,  ..., 0.5006, 0.0000, 0.6536],
         [0.8294, 0.8346, 0.0000,  ..., 0.8208, 0.7959, 0.

## Masking

### Implementing ReLU

ReLU is a common activation function used in neural networks. It's formula is max(x, 0), meaning, if x >= 0, then return x, else return 0

In [48]:
tensor = torch.tensor([[1, 2, -3],
                      [-4, 5, -6],
                       [7, -8, -9]])

In [49]:
tensor

tensor([[ 1,  2, -3],
        [-4,  5, -6],
        [ 7, -8, -9]])

In [52]:
tensor >= 0 # Mask used for Relu

tensor([[ True,  True, False],
        [False,  True, False],
        [ True, False, False]])

In [54]:
relu_tensor = tensor * (tensor >= 0)

In [55]:
relu_tensor

tensor([[1, 2, 0],
        [0, 5, 0],
        [7, 0, 0]])

### Implementing Thresholding

In [56]:
tensor

tensor([[ 1,  2, -3],
        [-4,  5, -6],
        [ 7, -8, -9]])

In [62]:
# Using 0 as the cutoff threshold.
output_tensor = (tensor >= 0) * 1

In [63]:
output_tensor

tensor([[1, 1, 0],
        [0, 1, 0],
        [1, 0, 0]])

## Experiment

Implement **Dropout** using masks.

In [64]:
tensor

tensor([[ 1,  2, -3],
        [-4,  5, -6],
        [ 7, -8, -9]])

In [67]:
dropout_threshold = 0.2

In [86]:
dropout_tensor = torch.rand(3, 3)

In [87]:
dropout_tensor

tensor([[0.5953, 0.0498, 0.1263],
        [0.7188, 0.1310, 0.3055],
        [0.2230, 0.3126, 0.9203]])

In [100]:
(dropout_tensor >= dropout_threshold)

tensor([[ True, False, False],
        [ True, False,  True],
        [ True,  True,  True]])

In [101]:
post_dropout_tensor = tensor * (dropout_tensor > dropout_threshold)

In [102]:
post_dropout_tensor

tensor([[ 1,  0,  0],
        [-4,  0, -6],
        [ 7, -8, -9]])