In [1]:
import torch

# Matrix Operations

**Goal:** Build intuition for matrix operations used in deep learning.

## Matrix Multiplication

**Rule:** The number of columns of first matrix should match the number of rows of the 2nd matrix

In [ ]:
# Create initial tensors
tensor1 = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

tensor2 = torch.tensor([[1, 2, 3, 4],
                        [5, 6, 7, 8],
                        [9, 10, 11, 12]])

tensor3 = torch.tensor([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9],
                        [10, 11, 12]])

**Experiments**

1. torch.matmul(tensor1, tensor2) = success
2. torch.matmul(tensor1, tensor3) = fail
3. torch.matmul(tensor2, tensor3) = success
4. torch.matmul(tensor3, tensor1) = success

In [ ]:
torch.matmul(tensor1, tensor2)

tensor([[ 38,  44,  50,  56],
        [ 83,  98, 113, 128],
        [128, 152, 176, 200]])

In [ ]:
torch.matmul(tensor1, tensor3)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x3 and 4x3)

In [ ]:
torch.matmul(tensor2, tensor3)

tensor([[ 70,  80,  90],
        [158, 184, 210],
        [246, 288, 330]])

In [ ]:
torch.matmul(tensor3, tensor1)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150],
        [138, 171, 204]])

**Observations**

1. torch.matmul(tensor1, tensor2) = success: Since 3 columns and 3 rows
2. torch.matmul(tensor1, tensor3) = fail: Since 3 columns and 4 rows
1. torch.matmul(tensor2, tensor3) = success: Since 4 columns and 4 rows
1. torch.matmul(tensor3, tensor1) = success: Since 3 columns and 3 rows

## Batch Matrix Multiplication

**Rule** For multi-dimensional matrices, for example with shape (b, n, m), the last 2 dimensions are used as the matrix shapes, and the leading dimensions are batch sizes/dimensions.

For batches of shapes -> (b, n, m) and (b, m, p), we will get result in the shape of (b, n, p).

In [ ]:
# Create initial tensors
batch1 = torch.rand((3, 3, 4))
batch2 = torch.rand((3, 4, 5))
batch3 = torch.rand((3, 5, 3))

**Success or fail Experiments**

1. torch.matmul(batch1, batch2) = success
2. torch.matmul(batch1, batch3) = fail
3. torch.matmul(batch2, batch3) = success
4. torch.matmul(tensor3, batch1) = success

**Speed Experiments**

1. torch.matmul(batch1, batch2) vs torch.bmm(batch1, batch2)

In [ ]:
torch.matmul(batch1, batch2)

tensor([[[1.5297, 1.1339, 1.4752, 1.6675, 0.3646],
         [0.6853, 0.2575, 0.7673, 0.6613, 0.1265],
         [1.5937, 1.0901, 1.4919, 1.7040, 0.3316]],

        [[0.8669, 0.6281, 0.8844, 1.1394, 0.5508],
         [0.8453, 0.3356, 0.1912, 0.7360, 0.2315],
         [1.0341, 0.4607, 0.7153, 0.9823, 0.6880]],

        [[1.3796, 0.5240, 1.1787, 0.7674, 0.9283],
         [1.0902, 0.3481, 0.9266, 0.5851, 0.8257],
         [0.9328, 0.5696, 0.6885, 0.7019, 0.4630]]])

In [ ]:
torch.matmul(batch1, batch3)

RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [3, 4] but got: [3, 5].

In [ ]:
torch.matmul(batch2, batch3)

tensor([[[1.9720, 1.0135, 1.4830],
         [2.1832, 1.2476, 1.2093],
         [2.4244, 1.1501, 1.7677],
         [1.9478, 1.0072, 1.1596]],

        [[1.2935, 2.1065, 1.5237],
         [0.3604, 0.7982, 0.6629],
         [0.5662, 0.7974, 0.6332],
         [0.7940, 1.7332, 1.2594]],

        [[1.7693, 0.9452, 1.5108],
         [2.1036, 1.1835, 1.9375],
         [1.8973, 0.8643, 1.7190],
         [0.8680, 0.4511, 0.8698]]])

In [ ]:
torch.matmul(batch3, batch1)

tensor([[[0.3730, 0.8220, 1.4384, 1.3143],
         [0.3043, 0.4424, 0.9501, 0.6507],
         [0.4581, 0.9495, 1.8196, 1.4810],
         [0.3007, 0.6355, 1.1591, 1.0041],
         [0.2478, 0.5138, 0.9054, 0.8171]],

        [[0.7991, 0.7018, 0.4736, 0.9725],
         [1.0184, 0.9956, 0.4698, 1.0203],
         [0.2023, 0.1926, 0.1973, 0.2861],
         [0.7269, 0.5818, 0.3688, 0.9056],
         [0.3791, 0.3862, 0.1132, 0.3157]],

        [[0.6944, 0.5020, 0.5438, 1.0079],
         [0.3660, 0.1872, 0.1244, 0.4328],
         [0.6384, 0.3959, 0.3556, 0.8175],
         [0.8582, 0.5599, 0.5406, 1.1511],
         [0.6997, 0.3419, 0.2035, 0.8042]]])

In [ ]:
%%time
torch.matmul(batch1, batch2)

CPU times: user 227 µs, sys: 28 µs, total: 255 µs
Wall time: 159 µs


tensor([[[1.5297, 1.1339, 1.4752, 1.6675, 0.3646],
         [0.6853, 0.2575, 0.7673, 0.6613, 0.1265],
         [1.5937, 1.0901, 1.4919, 1.7040, 0.3316]],

        [[0.8669, 0.6281, 0.8844, 1.1394, 0.5508],
         [0.8453, 0.3356, 0.1912, 0.7360, 0.2315],
         [1.0341, 0.4607, 0.7153, 0.9823, 0.6880]],

        [[1.3796, 0.5240, 1.1787, 0.7674, 0.9283],
         [1.0902, 0.3481, 0.9266, 0.5851, 0.8257],
         [0.9328, 0.5696, 0.6885, 0.7019, 0.4630]]])

In [ ]:
%%time
torch.bmm(batch1, batch2)

CPU times: user 206 µs, sys: 25 µs, total: 231 µs
Wall time: 373 µs


tensor([[[1.5297, 1.1339, 1.4752, 1.6675, 0.3646],
         [0.6853, 0.2575, 0.7673, 0.6613, 0.1265],
         [1.5937, 1.0901, 1.4919, 1.7040, 0.3316]],

        [[0.8669, 0.6281, 0.8844, 1.1394, 0.5508],
         [0.8453, 0.3356, 0.1912, 0.7360, 0.2315],
         [1.0341, 0.4607, 0.7153, 0.9823, 0.6880]],

        [[1.3796, 0.5240, 1.1787, 0.7674, 0.9283],
         [1.0902, 0.3481, 0.9266, 0.5851, 0.8257],
         [0.9328, 0.5696, 0.6885, 0.7019, 0.4630]]])

In [ ]:
# Larger batches
large_batch1 = torch.rand((1000, 300, 400))
large_batch2 = torch.rand((1000, 400, 500))

In [ ]:
%%time
torch.matmul(large_batch1, large_batch2)

CPU times: user 3.16 s, sys: 428 ms, total: 3.59 s
Wall time: 3.67 s


tensor([[[107.5703, 100.3676,  95.2432,  ...,  96.7841,  99.0756, 103.1841],
         [112.3162, 104.9585, 101.8629,  ..., 101.8576, 101.4243, 104.3139],
         [107.4932,  99.5279, 100.8701,  ..., 101.7412, 103.1789, 106.4170],
         ...,
         [105.0373,  98.4182, 100.3800,  ..., 103.1750, 101.6716, 100.0412],
         [107.7891, 101.6321,  99.6014,  ...,  95.6318, 101.0515, 103.2293],
         [106.7840,  99.6760,  97.9670,  ..., 100.9810, 101.0769, 103.8237]],

        [[101.9417, 105.4905, 102.2919,  ...,  98.1804, 101.6204, 108.1620],
         [105.2632, 101.5984, 105.9244,  ..., 101.6615, 102.9489, 108.8423],
         [ 98.5308,  98.6323,  94.6098,  ...,  94.2619,  94.5893,  99.4510],
         ...,
         [106.0452, 105.9926, 103.2714,  ..., 102.5617, 104.9808, 112.4676],
         [104.5884, 101.4998, 102.0035,  ...,  97.0850, 101.4837, 106.0491],
         [104.2217, 104.3837, 105.5231,  ..., 104.4651, 103.8788, 109.6400]],

        [[107.1277,  99.2429,  99.3145,  ...

In [ ]:
%%time
torch.bmm(large_batch1, large_batch2)

CPU times: user 2.2 s, sys: 367 ms, total: 2.57 s
Wall time: 2.57 s


tensor([[[107.5703, 100.3676,  95.2432,  ...,  96.7841,  99.0756, 103.1841],
         [112.3162, 104.9585, 101.8629,  ..., 101.8576, 101.4243, 104.3139],
         [107.4932,  99.5279, 100.8701,  ..., 101.7412, 103.1789, 106.4170],
         ...,
         [105.0373,  98.4182, 100.3800,  ..., 103.1750, 101.6716, 100.0412],
         [107.7891, 101.6321,  99.6014,  ...,  95.6318, 101.0515, 103.2293],
         [106.7840,  99.6760,  97.9670,  ..., 100.9810, 101.0769, 103.8237]],

        [[101.9417, 105.4905, 102.2919,  ...,  98.1804, 101.6204, 108.1620],
         [105.2632, 101.5984, 105.9244,  ..., 101.6615, 102.9489, 108.8423],
         [ 98.5308,  98.6323,  94.6098,  ...,  94.2619,  94.5893,  99.4510],
         ...,
         [106.0452, 105.9926, 103.2714,  ..., 102.5617, 104.9808, 112.4676],
         [104.5884, 101.4998, 102.0035,  ...,  97.0850, 101.4837, 106.0491],
         [104.2217, 104.3837, 105.5231,  ..., 104.4651, 103.8788, 109.6400]],

        [[107.1277,  99.2429,  99.3145,  ...

#### Observations

**Success or fail Experiments**

1. torch.matmul(batch1, batch2) = success: since the last 2 shapes are (3,4) and (4, 5). The leading dimension is the size of the batch. So, since the number of columns in batch1's matrices and number of rows in batch2's matrices are equal, this is a success.

2. torch.matmul(batch1, batch3) = fail: since the last 2 shapes are (3,4) and (5, 3). The leading dimension is the size of the batch. So, since the number of columns in batch1's matrices and number of rows in batch3's matrices are unequal, this is a failure.
3. torch.matmul(batch2, batch3) = success: since the last 2 shapes are (4, 5) and (5, 3). The leading dimension is the size of the batch. So, since the number of columns in batch2's matrices and number of rows in batch3's matrices are equal, this is a success.
4. torch.matmul(tensor3, batch1) = success: since the last 2 shapes are (5, 3) and (3, 4). The leading dimension is the size of the batch. So, since the number of columns in batch3's matrices and number of rows in batch1's matrices are equal, this is a success.

**Speed Experiments**

1. torch.matmul(batch1, batch2) vs torch.bmm(batch1, batch2): There's no clear winner for smaller batches, but for larger batches, bmm consistently wins. But it's still competitive

## Dot Product

**Rule:** Dot product for 2 vectors v and w are as follows:
- v = [v1, v2, v3]
- w = [w1, w2, w3]

```
v.w = v1*w1 + v2*w2 + v2*w2
```

For 2 matrices, when we find the dot product, we get a resultant matrix which is the dot product of the corresponding row from 1st matrix and column from 2nd matrix

#### Experiment:

1. create 2 matrices of shape (100, 90) and (90, 100)
2. run a python loop for matrix multiplication
3. run matmul.
4. test the time

In [ ]:
# input tensors
tensor1 = torch.rand((100, 90))
tensor2 = torch.rand((90, 100))

In [ ]:
%%time
# Python loop
result = torch.zeros((100, 100))

for i in range(100):
    for j in range(100):
        for k in range(90):
            result[i, j] += tensor1[i, k] * tensor2[k, j]
result

CPU times: user 21.2 s, sys: 20 ms, total: 21.2 s
Wall time: 21.4 s


tensor([[23.3564, 23.6001, 22.8002,  ..., 20.5922, 22.2135, 23.3808],
        [24.6103, 23.8366, 22.4081,  ..., 21.1169, 20.9989, 24.8756],
        [25.4401, 24.8996, 23.2851,  ..., 23.2483, 23.8879, 25.7683],
        ...,
        [22.3914, 22.3956, 21.6505,  ..., 19.6316, 21.5398, 23.3852],
        [22.5729, 24.6789, 20.0521,  ..., 20.6949, 20.8757, 21.5178],
        [24.4882, 24.5954, 23.3051,  ..., 23.6998, 23.7688, 25.4037]])

In [ ]:
%%time
result = torch.matmul(tensor1, tensor2)
result

CPU times: user 1.35 ms, sys: 0 ns, total: 1.35 ms
Wall time: 1.63 ms


tensor([[23.3564, 23.6001, 22.8002,  ..., 20.5922, 22.2135, 23.3808],
        [24.6103, 23.8366, 22.4081,  ..., 21.1169, 20.9989, 24.8756],
        [25.4401, 24.8996, 23.2851,  ..., 23.2483, 23.8879, 25.7683],
        ...,
        [22.3914, 22.3956, 21.6505,  ..., 19.6316, 21.5398, 23.3852],
        [22.5729, 24.6789, 20.0521,  ..., 20.6949, 20.8757, 21.5178],
        [24.4882, 24.5954, 23.3051,  ..., 23.6998, 23.7688, 25.4037]])

#### Observation

Python loop is much slower than matmul. This is because the loop is sequentially multiplying each element pair in the matrices, while matmul uses optimised pytorch parallel matrix multiplication

## Normalization
1. **L1 Normalization:**
  - divides all the elements in the vector by the sum of the elements
  - Creates Sparse matrix with many values close to 0
  - Good for cases where we can just ignore irrelevant features

2. **L2 Normalization:**
  - divides all elements by the standard deviation of the elements
  - Scales the vector to a unit length of 1 while preserving the relative direction of the data points.
  - Best for algorithms where magnitude needs to be preserved, such as neural networks or distance calculations using dot products.

#### L1 Normalization

In [ ]:
x = torch.rand(100, 3, 4)

In [ ]:
x

tensor([[[0.2504, 0.2387, 0.4888, 0.5787],
         [0.3624, 0.5982, 0.5209, 0.1008],
         [0.3830, 0.5520, 0.3230, 0.3554]],

        [[0.2446, 0.0554, 0.6057, 0.0442],
         [0.9303, 0.4219, 0.8065, 0.2379],
         [0.6479, 0.1040, 0.1236, 0.6092]],

        [[0.6216, 0.0462, 0.0492, 0.2124],
         [0.7116, 0.9423, 0.7764, 0.8261],
         [0.7375, 0.2401, 0.8009, 0.6444]],

        ...,

        [[0.9577, 0.5213, 0.1358, 0.8646],
         [0.3566, 0.2995, 0.8592, 0.2664],
         [0.5792, 0.5486, 0.7166, 0.2195]],

        [[0.3909, 0.6791, 0.0448, 0.5623],
         [0.9336, 0.5337, 0.8974, 0.5405],
         [0.4089, 0.1005, 0.5915, 0.9067]],

        [[0.6869, 0.2429, 0.7962, 0.8922],
         [0.4029, 0.7391, 0.4069, 0.9041],
         [0.9937, 0.0540, 0.2394, 0.9121]]])

In [ ]:
x_norm = x / x.sum()

In [ ]:
x_norm

tensor([[[4.2899e-04, 4.0884e-04, 8.3725e-04, 9.9129e-04],
         [6.2078e-04, 1.0246e-03, 8.9222e-04, 1.7260e-04],
         [6.5604e-04, 9.4548e-04, 5.5334e-04, 6.0883e-04]],

        [[4.1897e-04, 9.4910e-05, 1.0375e-03, 7.5727e-05],
         [1.5935e-03, 7.2268e-04, 1.3815e-03, 4.0753e-04],
         [1.1098e-03, 1.7823e-04, 2.1181e-04, 1.0436e-03]],

        [[1.0648e-03, 7.9120e-05, 8.4329e-05, 3.6387e-04],
         [1.2189e-03, 1.6141e-03, 1.3299e-03, 1.4152e-03],
         [1.2634e-03, 4.1128e-04, 1.3719e-03, 1.1038e-03]],

        ...,

        [[1.6405e-03, 8.9299e-04, 2.3261e-04, 1.4811e-03],
         [6.1081e-04, 5.1298e-04, 1.4718e-03, 4.5626e-04],
         [9.9217e-04, 9.3976e-04, 1.2275e-03, 3.7597e-04]],

        [[6.6960e-04, 1.1632e-03, 7.6794e-05, 9.6315e-04],
         [1.5993e-03, 9.1427e-04, 1.5371e-03, 9.2587e-04],
         [7.0052e-04, 1.7223e-04, 1.0132e-03, 1.5532e-03]],

        [[1.1767e-03, 4.1607e-04, 1.3639e-03, 1.5282e-03],
         [6.9008e-04, 1.2660e-03

In [ ]:
x_norm.shape

torch.Size([100, 3, 4])

In [ ]:
x_norm[(x_norm <= 0 + 0.001) & (x_norm >= 0 - 0.001)].shape

torch.Size([721])

As you can see, there are a lot of elements close to or equal to 0

#### L2 Normalization

In [ ]:
x = torch.rand(100, 3, 4)

In [ ]:
x

tensor([[[0.5294, 0.7355, 0.4350, 0.4703],
         [0.1169, 0.8945, 0.3241, 0.4768],
         [0.6926, 0.1957, 0.4413, 0.1127]],

        [[0.4702, 0.7782, 0.0384, 0.1205],
         [0.6917, 0.5747, 0.0107, 0.1419],
         [0.2925, 0.7299, 0.5801, 0.6998]],

        [[0.2282, 0.1828, 0.4123, 0.8484],
         [0.5110, 0.1311, 0.1857, 0.7576],
         [0.9067, 0.7283, 0.5140, 0.9577]],

        ...,

        [[0.6768, 0.7511, 0.9089, 0.2149],
         [0.3478, 0.9827, 0.7491, 0.5484],
         [0.1584, 0.6146, 0.9733, 0.0516]],

        [[0.3715, 0.2914, 0.2337, 0.3629],
         [0.1992, 0.1760, 0.4811, 0.2814],
         [0.6714, 0.2159, 0.2256, 0.5802]],

        [[0.1197, 0.6005, 0.5415, 0.5103],
         [0.9406, 0.7473, 0.1185, 0.3967],
         [0.0829, 0.5446, 0.6946, 0.8170]]])

In [ ]:
x_norm = x / x.std()

In [ ]:
x_norm

tensor([[[1.7924, 2.4900, 1.4727, 1.5921],
         [0.3958, 3.0283, 1.0972, 1.6142],
         [2.3447, 0.6626, 1.4940, 0.3816]],

        [[1.5918, 2.6345, 0.1300, 0.4081],
         [2.3417, 1.9458, 0.0364, 0.4805],
         [0.9902, 2.4712, 1.9639, 2.3693]],

        [[0.7726, 0.6187, 1.3958, 2.8722],
         [1.7299, 0.4437, 0.6286, 2.5647],
         [3.0695, 2.4657, 1.7403, 3.2424]],

        ...,

        [[2.2913, 2.5428, 3.0771, 0.7275],
         [1.1776, 3.3270, 2.5361, 1.8566],
         [0.5361, 2.0809, 3.2951, 0.1747]],

        [[1.2578, 0.9866, 0.7913, 1.2285],
         [0.6744, 0.5960, 1.6286, 0.9527],
         [2.2729, 0.7309, 0.7638, 1.9644]],

        [[0.4054, 2.0329, 1.8333, 1.7277],
         [3.1843, 2.5299, 0.4011, 1.3430],
         [0.2805, 1.8438, 2.3517, 2.7660]]])

In [ ]:
x_norm[(x_norm <= 0 + 0.001) & (x_norm >= 0 - 0.001)].shape

torch.Size([1])

L2 Norm magnifies the elements which have higher magnitudes, but doesn't scale the lesser features down to 0, preserving whatever small amount of info it provides

# Implementations

## Cosine Similarity

In [2]:
x = torch.rand(3, 3)
y = torch.rand(3, 3)

In [3]:
import numpy as np

In [4]:
(x*y).sum(dim=1)

tensor([0.7682, 0.8818, 0.2729])

In [22]:
x.unsqueeze(dim=1)

tensor([[[0.1064, 0.9449, 0.6723]],

        [[0.8363, 0.7374, 0.1455]],

        [[0.5240, 0.4709, 0.4438]]])

In [23]:
torch.matmul(x, y.T).diagonal()

tensor([0.7682, 0.8818, 0.2729])

In [29]:
np.sqrt((x * x).sum())

/tmp/ipykernel_790/1956134716.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  np.sqrt((x * x).sum())


tensor(1.8203)

In [30]:
torch.norm(x, p=2)

tensor(1.8203)

In [27]:
np.sqrt((y * y).sum())

/tmp/ipykernel_790/201666248.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  np.sqrt((y * y).sum())


tensor(1.3440)

In [28]:
torch.norm(y, p=2)

tensor(1.3440)

In [42]:
x

tensor([[0.1064, 0.9449, 0.6723],
        [0.8363, 0.7374, 0.1455],
        [0.5240, 0.4709, 0.4438]])

In [43]:
x*x

tensor([[0.0113, 0.8928, 0.4520],
        [0.6994, 0.5437, 0.0212],
        [0.2746, 0.2218, 0.1969]])

In [41]:
(x*x).sum(dim=1)

tensor([1.3561, 1.2643, 0.6933])

In [44]:
np.sqrt((x*x).sum(dim=1)) * np.sqrt((y*y).sum(dim=1))

/tmp/ipykernel_790/359913799.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  np.sqrt((x*x).sum(dim=1)) * np.sqrt((y*y).sum(dim=1))


tensor([0.8479, 1.2148, 0.2747])

In [35]:
torch.matmul(x, y.T).diagonal() / torch.cosine_similarity(x, y)

tensor([0.8479, 1.2148, 0.2747])

In [47]:
cosine_sim = torch.matmul(x, y.T).diagonal()/(np.sqrt((x*x).sum(dim=1)) * np.sqrt((y*y).sum(dim=1)))

/tmp/ipykernel_790/3378313752.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  cosine_sim = torch.matmul(x, y.T).diagonal()/(np.sqrt((x*x).sum(dim=1)) * np.sqrt((y*y).sum(dim=1)))


In [48]:
cosine_sim

tensor([0.9060, 0.7259, 0.9932])

In [49]:
torch.cosine_similarity(x, y)

tensor([0.9060, 0.7259, 0.9932])