In [1]:
import torch

# Matrix Operations

**Goal:** Build intuition for matrix operations used in deep learning.

## Matrix Multiplication

**Rule:** The number of columns of first matrix should match the number of columns of the 2nd matrix

In [ ]:
# Create initial tensors
tensor1 = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

tensor2 = torch.tensor([[1, 2, 3, 4],
                        [5, 6, 7, 8],
                        [9, 10, 11, 12]])

tensor3 = torch.tensor([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9],
                        [10, 11, 12]])

**Experiments**

1. torch.matmul(tensor1, tensor2) = success
2. torch.matmul(tensor1, tensor3) = fail
3. torch.matmul(tensor2, tensor3) = success
4. torch.matmul(tensor3, tensor1) = success

In [ ]:
torch.matmul(tensor1, tensor2)

tensor([[ 38,  44,  50,  56],
        [ 83,  98, 113, 128],
        [128, 152, 176, 200]])

In [ ]:
torch.matmul(tensor1, tensor3)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x3 and 4x3)

In [ ]:
torch.matmul(tensor2, tensor3)

tensor([[ 70,  80,  90],
        [158, 184, 210],
        [246, 288, 330]])

In [ ]:
torch.matmul(tensor3, tensor1)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150],
        [138, 171, 204]])

**Observations**

1. torch.matmul(tensor1, tensor2) = success: Since 3 columns and 3 rows
2. torch.matmul(tensor1, tensor3) = fail: Since 3 columns and 4 rows
1. torch.matmul(tensor2, tensor3) = success: Since 4 columns and 4 rows
1. torch.matmul(tensor3, tensor1) = success: Since 3 columns and 3 rows

## Batch Matrix Multiplication

**Rule** For multi-dimensional matrices, for example with shape (b, n, m), the last 2 dimensions are used as the matrix shapes, and the leading dimensions are batch sizes/dimensions.

For batches of shapes -> (b, n, m) and (b, m, p), we will get result in the shape of (b, n, p).

In [2]:
# Create initial tensors
batch1 = torch.rand((3, 3, 4))
batch2 = torch.rand((3, 4, 5))
batch3 = torch.rand((3, 5, 3))

**Success or fail Experiments**

1. torch.matmul(batch1, batch2) = success
2. torch.matmul(batch1, batch3) = fail
3. torch.matmul(batch2, batch3) = success
4. torch.matmul(tensor3, batch1) = success

**Speed Experiments**

1. torch.matmul(batch1, batch2) vs torch.bmm(batch1, batch2)

In [3]:
torch.matmul(batch1, batch2)

tensor([[[1.5297, 1.1339, 1.4752, 1.6675, 0.3646],
         [0.6853, 0.2575, 0.7673, 0.6613, 0.1265],
         [1.5937, 1.0901, 1.4919, 1.7040, 0.3316]],

        [[0.8669, 0.6281, 0.8844, 1.1394, 0.5508],
         [0.8453, 0.3356, 0.1912, 0.7360, 0.2315],
         [1.0341, 0.4607, 0.7153, 0.9823, 0.6880]],

        [[1.3796, 0.5240, 1.1787, 0.7674, 0.9283],
         [1.0902, 0.3481, 0.9266, 0.5851, 0.8257],
         [0.9328, 0.5696, 0.6885, 0.7019, 0.4630]]])

In [4]:
torch.matmul(batch1, batch3)

RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [3, 4] but got: [3, 5].

In [5]:
torch.matmul(batch2, batch3)

tensor([[[1.9720, 1.0135, 1.4830],
         [2.1832, 1.2476, 1.2093],
         [2.4244, 1.1501, 1.7677],
         [1.9478, 1.0072, 1.1596]],

        [[1.2935, 2.1065, 1.5237],
         [0.3604, 0.7982, 0.6629],
         [0.5662, 0.7974, 0.6332],
         [0.7940, 1.7332, 1.2594]],

        [[1.7693, 0.9452, 1.5108],
         [2.1036, 1.1835, 1.9375],
         [1.8973, 0.8643, 1.7190],
         [0.8680, 0.4511, 0.8698]]])

In [6]:
torch.matmul(batch3, batch1)

tensor([[[0.3730, 0.8220, 1.4384, 1.3143],
         [0.3043, 0.4424, 0.9501, 0.6507],
         [0.4581, 0.9495, 1.8196, 1.4810],
         [0.3007, 0.6355, 1.1591, 1.0041],
         [0.2478, 0.5138, 0.9054, 0.8171]],

        [[0.7991, 0.7018, 0.4736, 0.9725],
         [1.0184, 0.9956, 0.4698, 1.0203],
         [0.2023, 0.1926, 0.1973, 0.2861],
         [0.7269, 0.5818, 0.3688, 0.9056],
         [0.3791, 0.3862, 0.1132, 0.3157]],

        [[0.6944, 0.5020, 0.5438, 1.0079],
         [0.3660, 0.1872, 0.1244, 0.4328],
         [0.6384, 0.3959, 0.3556, 0.8175],
         [0.8582, 0.5599, 0.5406, 1.1511],
         [0.6997, 0.3419, 0.2035, 0.8042]]])

In [7]:
%%time
torch.matmul(batch1, batch2)

CPU times: user 227 µs, sys: 28 µs, total: 255 µs
Wall time: 159 µs


tensor([[[1.5297, 1.1339, 1.4752, 1.6675, 0.3646],
         [0.6853, 0.2575, 0.7673, 0.6613, 0.1265],
         [1.5937, 1.0901, 1.4919, 1.7040, 0.3316]],

        [[0.8669, 0.6281, 0.8844, 1.1394, 0.5508],
         [0.8453, 0.3356, 0.1912, 0.7360, 0.2315],
         [1.0341, 0.4607, 0.7153, 0.9823, 0.6880]],

        [[1.3796, 0.5240, 1.1787, 0.7674, 0.9283],
         [1.0902, 0.3481, 0.9266, 0.5851, 0.8257],
         [0.9328, 0.5696, 0.6885, 0.7019, 0.4630]]])

In [8]:
%%time
torch.bmm(batch1, batch2)

CPU times: user 206 µs, sys: 25 µs, total: 231 µs
Wall time: 373 µs


tensor([[[1.5297, 1.1339, 1.4752, 1.6675, 0.3646],
         [0.6853, 0.2575, 0.7673, 0.6613, 0.1265],
         [1.5937, 1.0901, 1.4919, 1.7040, 0.3316]],

        [[0.8669, 0.6281, 0.8844, 1.1394, 0.5508],
         [0.8453, 0.3356, 0.1912, 0.7360, 0.2315],
         [1.0341, 0.4607, 0.7153, 0.9823, 0.6880]],

        [[1.3796, 0.5240, 1.1787, 0.7674, 0.9283],
         [1.0902, 0.3481, 0.9266, 0.5851, 0.8257],
         [0.9328, 0.5696, 0.6885, 0.7019, 0.4630]]])

In [16]:
# Larger batches
large_batch1 = torch.rand((1000, 300, 400))
large_batch2 = torch.rand((1000, 400, 500))

In [19]:
%%time
torch.matmul(large_batch1, large_batch2)

CPU times: user 3.16 s, sys: 428 ms, total: 3.59 s
Wall time: 3.67 s


tensor([[[107.5703, 100.3676,  95.2432,  ...,  96.7841,  99.0756, 103.1841],
         [112.3162, 104.9585, 101.8629,  ..., 101.8576, 101.4243, 104.3139],
         [107.4932,  99.5279, 100.8701,  ..., 101.7412, 103.1789, 106.4170],
         ...,
         [105.0373,  98.4182, 100.3800,  ..., 103.1750, 101.6716, 100.0412],
         [107.7891, 101.6321,  99.6014,  ...,  95.6318, 101.0515, 103.2293],
         [106.7840,  99.6760,  97.9670,  ..., 100.9810, 101.0769, 103.8237]],

        [[101.9417, 105.4905, 102.2919,  ...,  98.1804, 101.6204, 108.1620],
         [105.2632, 101.5984, 105.9244,  ..., 101.6615, 102.9489, 108.8423],
         [ 98.5308,  98.6323,  94.6098,  ...,  94.2619,  94.5893,  99.4510],
         ...,
         [106.0452, 105.9926, 103.2714,  ..., 102.5617, 104.9808, 112.4676],
         [104.5884, 101.4998, 102.0035,  ...,  97.0850, 101.4837, 106.0491],
         [104.2217, 104.3837, 105.5231,  ..., 104.4651, 103.8788, 109.6400]],

        [[107.1277,  99.2429,  99.3145,  ...

In [20]:
%%time
torch.bmm(large_batch1, large_batch2)

CPU times: user 2.2 s, sys: 367 ms, total: 2.57 s
Wall time: 2.57 s


tensor([[[107.5703, 100.3676,  95.2432,  ...,  96.7841,  99.0756, 103.1841],
         [112.3162, 104.9585, 101.8629,  ..., 101.8576, 101.4243, 104.3139],
         [107.4932,  99.5279, 100.8701,  ..., 101.7412, 103.1789, 106.4170],
         ...,
         [105.0373,  98.4182, 100.3800,  ..., 103.1750, 101.6716, 100.0412],
         [107.7891, 101.6321,  99.6014,  ...,  95.6318, 101.0515, 103.2293],
         [106.7840,  99.6760,  97.9670,  ..., 100.9810, 101.0769, 103.8237]],

        [[101.9417, 105.4905, 102.2919,  ...,  98.1804, 101.6204, 108.1620],
         [105.2632, 101.5984, 105.9244,  ..., 101.6615, 102.9489, 108.8423],
         [ 98.5308,  98.6323,  94.6098,  ...,  94.2619,  94.5893,  99.4510],
         ...,
         [106.0452, 105.9926, 103.2714,  ..., 102.5617, 104.9808, 112.4676],
         [104.5884, 101.4998, 102.0035,  ...,  97.0850, 101.4837, 106.0491],
         [104.2217, 104.3837, 105.5231,  ..., 104.4651, 103.8788, 109.6400]],

        [[107.1277,  99.2429,  99.3145,  ...

#### Observations

**Success or fail Experiments**

1. torch.matmul(batch1, batch2) = success: since the last 2 shapes are (3,4) and (4, 5). The leading dimension is the size of the batch. So, since the number of columns in batch1's matrices and number of rows in batch2's matrices are equal, this is a success.

2. torch.matmul(batch1, batch3) = fail: since the last 2 shapes are (3,4) and (5, 3). The leading dimension is the size of the batch. So, since the number of columns in batch1's matrices and number of rows in batch3's matrices are unequal, this is a failure.
3. torch.matmul(batch2, batch3) = success: since the last 2 shapes are (4, 5) and (5, 3). The leading dimension is the size of the batch. So, since the number of columns in batch2's matrices and number of rows in batch3's matrices are equal, this is a success.
4. torch.matmul(tensor3, batch1) = success: since the last 2 shapes are (5, 3) and (3, 4). The leading dimension is the size of the batch. So, since the number of columns in batch3's matrices and number of rows in batch1's matrices are equal, this is a success.

**Speed Experiments**

1. torch.matmul(batch1, batch2) vs torch.bmm(batch1, batch2): There's no clear winner for smaller batches, but for larger batches, bmm consistently wins. But it's still competitive

## Dot Product

**Rule:** Dot product for 2 vectors v and w are as follows:
- v = [v1, v2, v3]
- w = [w1, w2, w3]

```
v.w = v1*w1 + v1*w1 + v1*w1
```

For 2 matrices, when we find the dot product, we get a resultant matrix which is the dot product of the corresponding row from 1st matrix and column from 2nd matrix

#### Experiment:

1. create 2 matrices of shape (100, 90) and (90, 100)
2. run a python loop for matrix multiplication
3. run matmul.
4. test the time

In [21]:
# input tensors
tensor1 = torch.rand((100, 90))
tensor2 = torch.rand((90, 100))

In [22]:
%%time
# Python loop
result = torch.zeros((100, 100))

for i in range(100):
    for j in range(100):
        for k in range(90):
            result[i, j] += tensor1[i, k] * tensor2[k, j]
result

CPU times: user 21.2 s, sys: 20 ms, total: 21.2 s
Wall time: 21.4 s


tensor([[23.3564, 23.6001, 22.8002,  ..., 20.5922, 22.2135, 23.3808],
        [24.6103, 23.8366, 22.4081,  ..., 21.1169, 20.9989, 24.8756],
        [25.4401, 24.8996, 23.2851,  ..., 23.2483, 23.8879, 25.7683],
        ...,
        [22.3914, 22.3956, 21.6505,  ..., 19.6316, 21.5398, 23.3852],
        [22.5729, 24.6789, 20.0521,  ..., 20.6949, 20.8757, 21.5178],
        [24.4882, 24.5954, 23.3051,  ..., 23.6998, 23.7688, 25.4037]])

In [23]:
%%time
result = torch.matmul(tensor1, tensor2)
result

CPU times: user 1.35 ms, sys: 0 ns, total: 1.35 ms
Wall time: 1.63 ms


tensor([[23.3564, 23.6001, 22.8002,  ..., 20.5922, 22.2135, 23.3808],
        [24.6103, 23.8366, 22.4081,  ..., 21.1169, 20.9989, 24.8756],
        [25.4401, 24.8996, 23.2851,  ..., 23.2483, 23.8879, 25.7683],
        ...,
        [22.3914, 22.3956, 21.6505,  ..., 19.6316, 21.5398, 23.3852],
        [22.5729, 24.6789, 20.0521,  ..., 20.6949, 20.8757, 21.5178],
        [24.4882, 24.5954, 23.3051,  ..., 23.6998, 23.7688, 25.4037]])

#### Observation

Python loop is much slower than matmul. This is because the loop is sequentially multiplying each element pair in the matrices, while matmul uses optimised pytorch parallel matrix multiplication

## Norms

# Implementations

## Cosine Similarity